name: Test

on:
  push:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build App
        run: make setup

      - name: Pest
        run: make pest